apiVersion: team.litellm.crossplane.io/v1alpha1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/member
  labels:
    testing.upbound.io/example-name: engineer
  name: engineer
spec:
  forProvider:
    maxBudgetInTeam: 200
    role: user
    teamId: ${litellm_team.engineering.id}
    userEmail: engineer@example.com
    userId: user_3
