/*
Copyright 2024 Corewire.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package controller contains the controller setup for provider-litellm.
// The managed-resource controllers are generated by running `make generate`
// and placed in this package as zz_setup.go (which replaces this stub).
package controller

import (
	tjcontroller "github.com/crossplane/upjet/v2/pkg/controller"
	ctrl "sigs.k8s.io/controller-runtime"
)

// Setup registers all managed-resource controllers with the controller manager.
//
// This is a placeholder stub. After running `make generate`, this file is
// replaced by a generated zz_setup.go that registers every LiteLLM managed
// resource controller (Model, Team, Key, etc.).
func Setup(mgr ctrl.Manager, o tjcontroller.Options) error {
	// Generated controllers are registered here after `make generate`.
	// Each controller calls its own Setup(mgr, o) function.
	return nil
}
