/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CredentialInitParameters struct {

	// Map of additional non-sensitive information about the credential.
	// Additional information about the credential
	// +mapType=granular
	CredentialInfo map[string]*string `json:"credentialInfo,omitempty" tf:"credential_info,omitempty"`

	// Name of the credential. This will be used as the identifier for the credential.
	// Name of the credential
	CredentialName *string `json:"credentialName,omitempty" tf:"credential_name,omitempty"`

	CredentialValues map[string]*string `json:"credentialValuesSecretRef,omitempty" tf:"-"`

	// Model ID associated with this credential.
	// Model ID associated with this credential
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`
}

type CredentialObservation struct {

	// Map of additional non-sensitive information about the credential.
	// Additional information about the credential
	// +mapType=granular
	CredentialInfo map[string]*string `json:"credentialInfo,omitempty" tf:"credential_info,omitempty"`

	// Name of the credential. This will be used as the identifier for the credential.
	// Name of the credential
	CredentialName *string `json:"credentialName,omitempty" tf:"credential_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Model ID associated with this credential.
	// Model ID associated with this credential
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`
}

type CredentialParameters struct {

	// Map of additional non-sensitive information about the credential.
	// Additional information about the credential
	// +kubebuilder:validation:Optional
	// +mapType=granular
	CredentialInfo map[string]*string `json:"credentialInfo,omitempty" tf:"credential_info,omitempty"`

	// Name of the credential. This will be used as the identifier for the credential.
	// Name of the credential
	// +kubebuilder:validation:Optional
	CredentialName *string `json:"credentialName,omitempty" tf:"credential_name,omitempty"`

	// Map of sensitive credential values such as API keys, tokens, etc.
	// Sensitive credential values (API keys, tokens, etc.)
	// +kubebuilder:validation:Optional
	CredentialValuesSecretRef v1.SecretReference `json:"credentialValuesSecretRef" tf:"-"`

	// Model ID associated with this credential.
	// Model ID associated with this credential
	// +kubebuilder:validation:Optional
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`
}

// CredentialSpec defines the desired state of Credential
type CredentialSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CredentialInitParameters `json:"initProvider,omitempty"`
}

// CredentialStatus defines the observed state of Credential.
type CredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Credential is the Schema for the Credentials API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Credential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentialName) || (has(self.initProvider) && has(self.initProvider.credentialName))",message="spec.forProvider.credentialName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentialValuesSecretRef)",message="spec.forProvider.credentialValuesSecretRef is a required parameter"
	Spec   CredentialSpec   `json:"spec"`
	Status CredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CredentialList contains a list of Credentials
type CredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Credential `json:"items"`
}

// Repository type metadata.
var (
	Credential_Kind             = "Credential"
	Credential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Credential_Kind}.String()
	Credential_KindAPIVersion   = Credential_Kind + "." + CRDGroupVersion.String()
	Credential_GroupVersionKind = CRDGroupVersion.WithKind(Credential_Kind)
)

func init() {
	SchemeBuilder.Register(&Credential{}, &CredentialList{})
}
