/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Credential) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Key) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *McpServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Model) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationMemberAdd) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Team) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamMemberAdd) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VectorStore) Hub() {}
