//go:build !ignore_autogenerated

/*
Copyright 2024 Corewire.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credential) DeepCopyInto(out *Credential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credential.
func (in *Credential) DeepCopy() *Credential {
	if in == nil {
		return nil
	}
	out := new(Credential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Credential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialInitParameters) DeepCopyInto(out *CredentialInitParameters) {
	*out = *in
	if in.CredentialInfo != nil {
		in, out := &in.CredentialInfo, &out.CredentialInfo
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.CredentialName != nil {
		in, out := &in.CredentialName, &out.CredentialName
		*out = new(string)
		**out = **in
	}
	if in.CredentialValues != nil {
		in, out := &in.CredentialValues, &out.CredentialValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialInitParameters.
func (in *CredentialInitParameters) DeepCopy() *CredentialInitParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialList) DeepCopyInto(out *CredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Credential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialList.
func (in *CredentialList) DeepCopy() *CredentialList {
	if in == nil {
		return nil
	}
	out := new(CredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialObservation) DeepCopyInto(out *CredentialObservation) {
	*out = *in
	if in.CredentialInfo != nil {
		in, out := &in.CredentialInfo, &out.CredentialInfo
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.CredentialName != nil {
		in, out := &in.CredentialName, &out.CredentialName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialObservation.
func (in *CredentialObservation) DeepCopy() *CredentialObservation {
	if in == nil {
		return nil
	}
	out := new(CredentialObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialParameters) DeepCopyInto(out *CredentialParameters) {
	*out = *in
	if in.CredentialInfo != nil {
		in, out := &in.CredentialInfo, &out.CredentialInfo
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.CredentialName != nil {
		in, out := &in.CredentialName, &out.CredentialName
		*out = new(string)
		**out = **in
	}
	in.CredentialValuesSecretRef.DeepCopyInto(&out.CredentialValuesSecretRef)
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialParameters.
func (in *CredentialParameters) DeepCopy() *CredentialParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialSpec) DeepCopyInto(out *CredentialSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialSpec.
func (in *CredentialSpec) DeepCopy() *CredentialSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialStatus) DeepCopyInto(out *CredentialStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialStatus.
func (in *CredentialStatus) DeepCopy() *CredentialStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Key) DeepCopyInto(out *Key) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Key.
func (in *Key) DeepCopy() *Key {
	if in == nil {
		return nil
	}
	out := new(Key)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Key) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyInitParameters) DeepCopyInto(out *KeyInitParameters) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AllowedCacheControls != nil {
		in, out := &in.AllowedCacheControls, &out.AllowedCacheControls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KeyAlias != nil {
		in, out := &in.KeyAlias, &out.KeyAlias
		*out = new(string)
		**out = **in
	}
	if in.KeySecretRef != nil {
		in, out := &in.KeySecretRef, &out.KeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.MaxParallelRequests != nil {
		in, out := &in.MaxParallelRequests, &out.MaxParallelRequests
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelMaxBudget != nil {
		in, out := &in.ModelMaxBudget, &out.ModelMaxBudget
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelRpmLimit != nil {
		in, out := &in.ModelRpmLimit, &out.ModelRpmLimit
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelTpmLimit != nil {
		in, out := &in.ModelTpmLimit, &out.ModelTpmLimit
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.SoftBudget != nil {
		in, out := &in.SoftBudget, &out.SoftBudget
		*out = new(float64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyInitParameters.
func (in *KeyInitParameters) DeepCopy() *KeyInitParameters {
	if in == nil {
		return nil
	}
	out := new(KeyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyList) DeepCopyInto(out *KeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Key, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyList.
func (in *KeyList) DeepCopy() *KeyList {
	if in == nil {
		return nil
	}
	out := new(KeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyObservation) DeepCopyInto(out *KeyObservation) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AllowedCacheControls != nil {
		in, out := &in.AllowedCacheControls, &out.AllowedCacheControls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KeyAlias != nil {
		in, out := &in.KeyAlias, &out.KeyAlias
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.MaxParallelRequests != nil {
		in, out := &in.MaxParallelRequests, &out.MaxParallelRequests
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelMaxBudget != nil {
		in, out := &in.ModelMaxBudget, &out.ModelMaxBudget
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelRpmLimit != nil {
		in, out := &in.ModelRpmLimit, &out.ModelRpmLimit
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelTpmLimit != nil {
		in, out := &in.ModelTpmLimit, &out.ModelTpmLimit
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.SoftBudget != nil {
		in, out := &in.SoftBudget, &out.SoftBudget
		*out = new(float64)
		**out = **in
	}
	if in.Spend != nil {
		in, out := &in.Spend, &out.Spend
		*out = new(float64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.TokenID != nil {
		in, out := &in.TokenID, &out.TokenID
		*out = new(string)
		**out = **in
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyObservation.
func (in *KeyObservation) DeepCopy() *KeyObservation {
	if in == nil {
		return nil
	}
	out := new(KeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyParameters) DeepCopyInto(out *KeyParameters) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AllowedCacheControls != nil {
		in, out := &in.AllowedCacheControls, &out.AllowedCacheControls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.KeyAlias != nil {
		in, out := &in.KeyAlias, &out.KeyAlias
		*out = new(string)
		**out = **in
	}
	if in.KeySecretRef != nil {
		in, out := &in.KeySecretRef, &out.KeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.MaxParallelRequests != nil {
		in, out := &in.MaxParallelRequests, &out.MaxParallelRequests
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelMaxBudget != nil {
		in, out := &in.ModelMaxBudget, &out.ModelMaxBudget
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelRpmLimit != nil {
		in, out := &in.ModelRpmLimit, &out.ModelRpmLimit
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ModelTpmLimit != nil {
		in, out := &in.ModelTpmLimit, &out.ModelTpmLimit
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.SoftBudget != nil {
		in, out := &in.SoftBudget, &out.SoftBudget
		*out = new(float64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyParameters.
func (in *KeyParameters) DeepCopy() *KeyParameters {
	if in == nil {
		return nil
	}
	out := new(KeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeySpec) DeepCopyInto(out *KeySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeySpec.
func (in *KeySpec) DeepCopy() *KeySpec {
	if in == nil {
		return nil
	}
	out := new(KeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyStatus) DeepCopyInto(out *KeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyStatus.
func (in *KeyStatus) DeepCopy() *KeyStatus {
	if in == nil {
		return nil
	}
	out := new(KeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelInitParameters) DeepCopyInto(out *ModelInitParameters) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.AdditionalLitellmParams != nil {
		in, out := &in.AdditionalLitellmParams, &out.AdditionalLitellmParams
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AwsAccessKeyIDSecretRef != nil {
		in, out := &in.AwsAccessKeyIDSecretRef, &out.AwsAccessKeyIDSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsRegionName != nil {
		in, out := &in.AwsRegionName, &out.AwsRegionName
		*out = new(string)
		**out = **in
	}
	if in.AwsRoleNameSecretRef != nil {
		in, out := &in.AwsRoleNameSecretRef, &out.AwsRoleNameSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsSecretAccessKeySecretRef != nil {
		in, out := &in.AwsSecretAccessKeySecretRef, &out.AwsSecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsSessionNameSecretRef != nil {
		in, out := &in.AwsSessionNameSecretRef, &out.AwsSessionNameSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BaseModel != nil {
		in, out := &in.BaseModel, &out.BaseModel
		*out = new(string)
		**out = **in
	}
	if in.CustomLlmProvider != nil {
		in, out := &in.CustomLlmProvider, &out.CustomLlmProvider
		*out = new(string)
		**out = **in
	}
	if in.InputCostPerMillionTokens != nil {
		in, out := &in.InputCostPerMillionTokens, &out.InputCostPerMillionTokens
		*out = new(float64)
		**out = **in
	}
	if in.InputCostPerPixel != nil {
		in, out := &in.InputCostPerPixel, &out.InputCostPerPixel
		*out = new(float64)
		**out = **in
	}
	if in.InputCostPerSecond != nil {
		in, out := &in.InputCostPerSecond, &out.InputCostPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.LitellmCredentialName != nil {
		in, out := &in.LitellmCredentialName, &out.LitellmCredentialName
		*out = new(string)
		**out = **in
	}
	if in.MergeReasoningContentInChoices != nil {
		in, out := &in.MergeReasoningContentInChoices, &out.MergeReasoningContentInChoices
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ModelAPIBase != nil {
		in, out := &in.ModelAPIBase, &out.ModelAPIBase
		*out = new(string)
		**out = **in
	}
	if in.ModelAPIKeySecretRef != nil {
		in, out := &in.ModelAPIKeySecretRef, &out.ModelAPIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	if in.OutputCostPerMillionTokens != nil {
		in, out := &in.OutputCostPerMillionTokens, &out.OutputCostPerMillionTokens
		*out = new(float64)
		**out = **in
	}
	if in.OutputCostPerPixel != nil {
		in, out := &in.OutputCostPerPixel, &out.OutputCostPerPixel
		*out = new(float64)
		**out = **in
	}
	if in.OutputCostPerSecond != nil {
		in, out := &in.OutputCostPerSecond, &out.OutputCostPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.PricingBaseModel != nil {
		in, out := &in.PricingBaseModel, &out.PricingBaseModel
		*out = new(string)
		**out = **in
	}
	if in.ReasoningEffort != nil {
		in, out := &in.ReasoningEffort, &out.ReasoningEffort
		*out = new(string)
		**out = **in
	}
	if in.Rpm != nil {
		in, out := &in.Rpm, &out.Rpm
		*out = new(float64)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.ThinkingBudgetTokens != nil {
		in, out := &in.ThinkingBudgetTokens, &out.ThinkingBudgetTokens
		*out = new(float64)
		**out = **in
	}
	if in.ThinkingEnabled != nil {
		in, out := &in.ThinkingEnabled, &out.ThinkingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.Tpm != nil {
		in, out := &in.Tpm, &out.Tpm
		*out = new(float64)
		**out = **in
	}
	if in.VertexCredentialsSecretRef != nil {
		in, out := &in.VertexCredentialsSecretRef, &out.VertexCredentialsSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.VertexLocationSecretRef != nil {
		in, out := &in.VertexLocationSecretRef, &out.VertexLocationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.VertexProjectSecretRef != nil {
		in, out := &in.VertexProjectSecretRef, &out.VertexProjectSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInitParameters.
func (in *ModelInitParameters) DeepCopy() *ModelInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelObservation) DeepCopyInto(out *ModelObservation) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.AdditionalLitellmParams != nil {
		in, out := &in.AdditionalLitellmParams, &out.AdditionalLitellmParams
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AwsRegionName != nil {
		in, out := &in.AwsRegionName, &out.AwsRegionName
		*out = new(string)
		**out = **in
	}
	if in.BaseModel != nil {
		in, out := &in.BaseModel, &out.BaseModel
		*out = new(string)
		**out = **in
	}
	if in.CustomLlmProvider != nil {
		in, out := &in.CustomLlmProvider, &out.CustomLlmProvider
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InputCostPerMillionTokens != nil {
		in, out := &in.InputCostPerMillionTokens, &out.InputCostPerMillionTokens
		*out = new(float64)
		**out = **in
	}
	if in.InputCostPerPixel != nil {
		in, out := &in.InputCostPerPixel, &out.InputCostPerPixel
		*out = new(float64)
		**out = **in
	}
	if in.InputCostPerSecond != nil {
		in, out := &in.InputCostPerSecond, &out.InputCostPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.LitellmCredentialName != nil {
		in, out := &in.LitellmCredentialName, &out.LitellmCredentialName
		*out = new(string)
		**out = **in
	}
	if in.MergeReasoningContentInChoices != nil {
		in, out := &in.MergeReasoningContentInChoices, &out.MergeReasoningContentInChoices
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ModelAPIBase != nil {
		in, out := &in.ModelAPIBase, &out.ModelAPIBase
		*out = new(string)
		**out = **in
	}
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	if in.OutputCostPerMillionTokens != nil {
		in, out := &in.OutputCostPerMillionTokens, &out.OutputCostPerMillionTokens
		*out = new(float64)
		**out = **in
	}
	if in.OutputCostPerPixel != nil {
		in, out := &in.OutputCostPerPixel, &out.OutputCostPerPixel
		*out = new(float64)
		**out = **in
	}
	if in.OutputCostPerSecond != nil {
		in, out := &in.OutputCostPerSecond, &out.OutputCostPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.PricingBaseModel != nil {
		in, out := &in.PricingBaseModel, &out.PricingBaseModel
		*out = new(string)
		**out = **in
	}
	if in.ReasoningEffort != nil {
		in, out := &in.ReasoningEffort, &out.ReasoningEffort
		*out = new(string)
		**out = **in
	}
	if in.Rpm != nil {
		in, out := &in.Rpm, &out.Rpm
		*out = new(float64)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.ThinkingBudgetTokens != nil {
		in, out := &in.ThinkingBudgetTokens, &out.ThinkingBudgetTokens
		*out = new(float64)
		**out = **in
	}
	if in.ThinkingEnabled != nil {
		in, out := &in.ThinkingEnabled, &out.ThinkingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.Tpm != nil {
		in, out := &in.Tpm, &out.Tpm
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelObservation.
func (in *ModelObservation) DeepCopy() *ModelObservation {
	if in == nil {
		return nil
	}
	out := new(ModelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelParameters) DeepCopyInto(out *ModelParameters) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.AdditionalLitellmParams != nil {
		in, out := &in.AdditionalLitellmParams, &out.AdditionalLitellmParams
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AwsAccessKeyIDSecretRef != nil {
		in, out := &in.AwsAccessKeyIDSecretRef, &out.AwsAccessKeyIDSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsRegionName != nil {
		in, out := &in.AwsRegionName, &out.AwsRegionName
		*out = new(string)
		**out = **in
	}
	if in.AwsRoleNameSecretRef != nil {
		in, out := &in.AwsRoleNameSecretRef, &out.AwsRoleNameSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsSecretAccessKeySecretRef != nil {
		in, out := &in.AwsSecretAccessKeySecretRef, &out.AwsSecretAccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsSessionNameSecretRef != nil {
		in, out := &in.AwsSessionNameSecretRef, &out.AwsSessionNameSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BaseModel != nil {
		in, out := &in.BaseModel, &out.BaseModel
		*out = new(string)
		**out = **in
	}
	if in.CustomLlmProvider != nil {
		in, out := &in.CustomLlmProvider, &out.CustomLlmProvider
		*out = new(string)
		**out = **in
	}
	if in.InputCostPerMillionTokens != nil {
		in, out := &in.InputCostPerMillionTokens, &out.InputCostPerMillionTokens
		*out = new(float64)
		**out = **in
	}
	if in.InputCostPerPixel != nil {
		in, out := &in.InputCostPerPixel, &out.InputCostPerPixel
		*out = new(float64)
		**out = **in
	}
	if in.InputCostPerSecond != nil {
		in, out := &in.InputCostPerSecond, &out.InputCostPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.LitellmCredentialName != nil {
		in, out := &in.LitellmCredentialName, &out.LitellmCredentialName
		*out = new(string)
		**out = **in
	}
	if in.MergeReasoningContentInChoices != nil {
		in, out := &in.MergeReasoningContentInChoices, &out.MergeReasoningContentInChoices
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ModelAPIBase != nil {
		in, out := &in.ModelAPIBase, &out.ModelAPIBase
		*out = new(string)
		**out = **in
	}
	if in.ModelAPIKeySecretRef != nil {
		in, out := &in.ModelAPIKeySecretRef, &out.ModelAPIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	if in.OutputCostPerMillionTokens != nil {
		in, out := &in.OutputCostPerMillionTokens, &out.OutputCostPerMillionTokens
		*out = new(float64)
		**out = **in
	}
	if in.OutputCostPerPixel != nil {
		in, out := &in.OutputCostPerPixel, &out.OutputCostPerPixel
		*out = new(float64)
		**out = **in
	}
	if in.OutputCostPerSecond != nil {
		in, out := &in.OutputCostPerSecond, &out.OutputCostPerSecond
		*out = new(float64)
		**out = **in
	}
	if in.PricingBaseModel != nil {
		in, out := &in.PricingBaseModel, &out.PricingBaseModel
		*out = new(string)
		**out = **in
	}
	if in.ReasoningEffort != nil {
		in, out := &in.ReasoningEffort, &out.ReasoningEffort
		*out = new(string)
		**out = **in
	}
	if in.Rpm != nil {
		in, out := &in.Rpm, &out.Rpm
		*out = new(float64)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.ThinkingBudgetTokens != nil {
		in, out := &in.ThinkingBudgetTokens, &out.ThinkingBudgetTokens
		*out = new(float64)
		**out = **in
	}
	if in.ThinkingEnabled != nil {
		in, out := &in.ThinkingEnabled, &out.ThinkingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.Tpm != nil {
		in, out := &in.Tpm, &out.Tpm
		*out = new(float64)
		**out = **in
	}
	if in.VertexCredentialsSecretRef != nil {
		in, out := &in.VertexCredentialsSecretRef, &out.VertexCredentialsSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.VertexLocationSecretRef != nil {
		in, out := &in.VertexLocationSecretRef, &out.VertexLocationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.VertexProjectSecretRef != nil {
		in, out := &in.VertexProjectSecretRef, &out.VertexProjectSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelParameters.
func (in *ModelParameters) DeepCopy() *ModelParameters {
	if in == nil {
		return nil
	}
	out := new(ModelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationInitParameters) DeepCopyInto(out *OrganizationInitParameters) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OrganizationAlias != nil {
		in, out := &in.OrganizationAlias, &out.OrganizationAlias
		*out = new(string)
		**out = **in
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationInitParameters.
func (in *OrganizationInitParameters) DeepCopy() *OrganizationInitParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationObservation) DeepCopyInto(out *OrganizationObservation) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OrganizationAlias != nil {
		in, out := &in.OrganizationAlias, &out.OrganizationAlias
		*out = new(string)
		**out = **in
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationObservation.
func (in *OrganizationObservation) DeepCopy() *OrganizationObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationParameters) DeepCopyInto(out *OrganizationParameters) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OrganizationAlias != nil {
		in, out := &in.OrganizationAlias, &out.OrganizationAlias
		*out = new(string)
		**out = **in
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationParameters.
func (in *OrganizationParameters) DeepCopy() *OrganizationParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamInitParameters) DeepCopyInto(out *TeamInitParameters) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.TeamAlias != nil {
		in, out := &in.TeamAlias, &out.TeamAlias
		*out = new(string)
		**out = **in
	}
	if in.TeamMemberPermissions != nil {
		in, out := &in.TeamMemberPermissions, &out.TeamMemberPermissions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamInitParameters.
func (in *TeamInitParameters) DeepCopy() *TeamInitParameters {
	if in == nil {
		return nil
	}
	out := new(TeamInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamObservation) DeepCopyInto(out *TeamObservation) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.TeamAlias != nil {
		in, out := &in.TeamAlias, &out.TeamAlias
		*out = new(string)
		**out = **in
	}
	if in.TeamMemberPermissions != nil {
		in, out := &in.TeamMemberPermissions, &out.TeamMemberPermissions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamObservation.
func (in *TeamObservation) DeepCopy() *TeamObservation {
	if in == nil {
		return nil
	}
	out := new(TeamObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamParameters) DeepCopyInto(out *TeamParameters) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.RpmLimit != nil {
		in, out := &in.RpmLimit, &out.RpmLimit
		*out = new(float64)
		**out = **in
	}
	if in.TeamAlias != nil {
		in, out := &in.TeamAlias, &out.TeamAlias
		*out = new(string)
		**out = **in
	}
	if in.TeamMemberPermissions != nil {
		in, out := &in.TeamMemberPermissions, &out.TeamMemberPermissions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TpmLimit != nil {
		in, out := &in.TpmLimit, &out.TpmLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamParameters.
func (in *TeamParameters) DeepCopy() *TeamParameters {
	if in == nil {
		return nil
	}
	out := new(TeamParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}
