/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KeyInitParameters struct {

	// Map of model aliases. This allows you to create custom names for models when using this key.
	// +mapType=granular
	Aliases map[string]*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// List of allowed cache control directives. This can be used to control caching behavior for requests made with this key.
	AllowedCacheControls []*string `json:"allowedCacheControls,omitempty" tf:"allowed_cache_controls,omitempty"`

	// Whether this key is blocked. If set to true, the key will be unable to make any requests.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget (e.g., "monthly", "weekly"). This defines the time period for which the max_budget applies.
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Configuration options for this key. This can be used to set key-specific settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Duration for which this key is valid. This sets an expiration time for the key.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// List of guardrails applied to this key. This can be used to enforce certain safety or quality checks.
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Alias for this key. This provides a human-readable identifier for the key.
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The generated API key. This is the actual key value that will be used for authentication.
	KeySecretRef *v1.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// Maximum budget for this key. This sets an upper limit on the total spend allowed for this key.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// Maximum number of parallel requests allowed for this key. This helps in controlling concurrent usage.
	MaxParallelRequests *float64 `json:"maxParallelRequests,omitempty" tf:"max_parallel_requests,omitempty"`

	// Metadata associated with this key. This can be used to store additional, custom information about the key.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Maximum budget per model. This allows setting different budget limits for each model.
	// +mapType=granular
	ModelMaxBudget map[string]*float64 `json:"modelMaxBudget,omitempty" tf:"model_max_budget,omitempty"`

	// Requests per minute limit per model. This allows setting different RPM limits for each model.
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Tokens per minute limit per model. This allows setting different TPM limits for each model.
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of models that can be used with this key. This restricts the key to only use the specified models.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// Permissions associated with this key. This defines what actions are allowed with this key.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Requests per minute limit for this key. This sets a rate limit based on the number of API calls.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Soft budget limit for this key. This can be used to set a warning threshold before reaching the max_budget.
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// List of tags associated with this key. This can be used for organization and filtering of keys.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Team ID associated with this key. This links the key to a specific team in the LiteLLM system.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit for this key. This sets a rate limit based on the number of tokens processed.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// User ID associated with this key. This links the key to a specific user in the LiteLLM system.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KeyObservation struct {

	// Map of model aliases. This allows you to create custom names for models when using this key.
	// +mapType=granular
	Aliases map[string]*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// List of allowed cache control directives. This can be used to control caching behavior for requests made with this key.
	AllowedCacheControls []*string `json:"allowedCacheControls,omitempty" tf:"allowed_cache_controls,omitempty"`

	// Whether this key is blocked. If set to true, the key will be unable to make any requests.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget (e.g., "monthly", "weekly"). This defines the time period for which the max_budget applies.
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Configuration options for this key. This can be used to set key-specific settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Duration for which this key is valid. This sets an expiration time for the key.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// List of guardrails applied to this key. This can be used to enforce certain safety or quality checks.
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Alias for this key. This provides a human-readable identifier for the key.
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// Maximum budget for this key. This sets an upper limit on the total spend allowed for this key.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// Maximum number of parallel requests allowed for this key. This helps in controlling concurrent usage.
	MaxParallelRequests *float64 `json:"maxParallelRequests,omitempty" tf:"max_parallel_requests,omitempty"`

	// Metadata associated with this key. This can be used to store additional, custom information about the key.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Maximum budget per model. This allows setting different budget limits for each model.
	// +mapType=granular
	ModelMaxBudget map[string]*float64 `json:"modelMaxBudget,omitempty" tf:"model_max_budget,omitempty"`

	// Requests per minute limit per model. This allows setting different RPM limits for each model.
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Tokens per minute limit per model. This allows setting different TPM limits for each model.
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of models that can be used with this key. This restricts the key to only use the specified models.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// Permissions associated with this key. This defines what actions are allowed with this key.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Requests per minute limit for this key. This sets a rate limit based on the number of API calls.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Soft budget limit for this key. This can be used to set a warning threshold before reaching the max_budget.
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// The current spend for this key. This reflects the total amount spent using this key so far.
	Spend *float64 `json:"spend,omitempty" tf:"spend,omitempty"`

	// List of tags associated with this key. This can be used for organization and filtering of keys.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Team ID associated with this key. This links the key to a specific team in the LiteLLM system.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`

	// Tokens per minute limit for this key. This sets a rate limit based on the number of tokens processed.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// User ID associated with this key. This links the key to a specific user in the LiteLLM system.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KeyParameters struct {

	// Map of model aliases. This allows you to create custom names for models when using this key.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Aliases map[string]*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// List of allowed cache control directives. This can be used to control caching behavior for requests made with this key.
	// +kubebuilder:validation:Optional
	AllowedCacheControls []*string `json:"allowedCacheControls,omitempty" tf:"allowed_cache_controls,omitempty"`

	// Whether this key is blocked. If set to true, the key will be unable to make any requests.
	// +kubebuilder:validation:Optional
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget (e.g., "monthly", "weekly"). This defines the time period for which the max_budget applies.
	// +kubebuilder:validation:Optional
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Configuration options for this key. This can be used to set key-specific settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Duration for which this key is valid. This sets an expiration time for the key.
	// +kubebuilder:validation:Optional
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// List of guardrails applied to this key. This can be used to enforce certain safety or quality checks.
	// +kubebuilder:validation:Optional
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Alias for this key. This provides a human-readable identifier for the key.
	// +kubebuilder:validation:Optional
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The generated API key. This is the actual key value that will be used for authentication.
	// +kubebuilder:validation:Optional
	KeySecretRef *v1.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// Maximum budget for this key. This sets an upper limit on the total spend allowed for this key.
	// +kubebuilder:validation:Optional
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// Maximum number of parallel requests allowed for this key. This helps in controlling concurrent usage.
	// +kubebuilder:validation:Optional
	MaxParallelRequests *float64 `json:"maxParallelRequests,omitempty" tf:"max_parallel_requests,omitempty"`

	// Metadata associated with this key. This can be used to store additional, custom information about the key.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Maximum budget per model. This allows setting different budget limits for each model.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelMaxBudget map[string]*float64 `json:"modelMaxBudget,omitempty" tf:"model_max_budget,omitempty"`

	// Requests per minute limit per model. This allows setting different RPM limits for each model.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Tokens per minute limit per model. This allows setting different TPM limits for each model.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of models that can be used with this key. This restricts the key to only use the specified models.
	// +kubebuilder:validation:Optional
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// Permissions associated with this key. This defines what actions are allowed with this key.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Requests per minute limit for this key. This sets a rate limit based on the number of API calls.
	// +kubebuilder:validation:Optional
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Soft budget limit for this key. This can be used to set a warning threshold before reaching the max_budget.
	// +kubebuilder:validation:Optional
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// List of tags associated with this key. This can be used for organization and filtering of keys.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Team ID associated with this key. This links the key to a specific team in the LiteLLM system.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit for this key. This sets a rate limit based on the number of tokens processed.
	// +kubebuilder:validation:Optional
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// User ID associated with this key. This links the key to a specific user in the LiteLLM system.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// KeySpec defines the desired state of Key
type KeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeyInitParameters `json:"initProvider,omitempty"`
}

// KeyStatus defines the observed state of Key.
type KeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Key is the Schema for the Keys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Key struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KeySpec   `json:"spec"`
	Status            KeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeyList contains a list of Keys
type KeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Key `json:"items"`
}

// Repository type metadata.
var (
	Key_Kind             = "Key"
	Key_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Key_Kind}.String()
	Key_KindAPIVersion   = Key_Kind + "." + CRDGroupVersion.String()
	Key_GroupVersionKind = CRDGroupVersion.WithKind(Key_Kind)
)

func init() {
	SchemeBuilder.Register(&Key{}, &KeyList{})
}
