/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type McpInfoInitParameters struct {

	// Description in MCP info.
	// Description in MCP info
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Logo URL for the MCP server.
	// Logo URL for the MCP server
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Cost information for MCP server tools
	McpServerCostInfo []McpServerCostInfoInitParameters `json:"mcpServerCostInfo,omitempty" tf:"mcp_server_cost_info,omitempty"`

	// Server name in MCP info.
	// Server name in MCP info
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`
}

type McpInfoObservation struct {

	// Description in MCP info.
	// Description in MCP info
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Logo URL for the MCP server.
	// Logo URL for the MCP server
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Cost information for MCP server tools
	McpServerCostInfo []McpServerCostInfoObservation `json:"mcpServerCostInfo,omitempty" tf:"mcp_server_cost_info,omitempty"`

	// Server name in MCP info.
	// Server name in MCP info
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`
}

type McpInfoParameters struct {

	// Description in MCP info.
	// Description in MCP info
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Logo URL for the MCP server.
	// Logo URL for the MCP server
	// +kubebuilder:validation:Optional
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Cost information for MCP server tools
	// +kubebuilder:validation:Optional
	McpServerCostInfo []McpServerCostInfoParameters `json:"mcpServerCostInfo,omitempty" tf:"mcp_server_cost_info,omitempty"`

	// Server name in MCP info.
	// Server name in MCP info
	// +kubebuilder:validation:Optional
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`
}

type McpServerCostInfoInitParameters struct {

	// Default cost per query for all tools.
	// Default cost per query
	DefaultCostPerQuery *float64 `json:"defaultCostPerQuery,omitempty" tf:"default_cost_per_query,omitempty"`

	// Map of specific tool names to their cost per query.
	// Map of tool names to their cost per query
	// +mapType=granular
	ToolNameToCostPerQuery map[string]*float64 `json:"toolNameToCostPerQuery,omitempty" tf:"tool_name_to_cost_per_query,omitempty"`
}

type McpServerCostInfoObservation struct {

	// Default cost per query for all tools.
	// Default cost per query
	DefaultCostPerQuery *float64 `json:"defaultCostPerQuery,omitempty" tf:"default_cost_per_query,omitempty"`

	// Map of specific tool names to their cost per query.
	// Map of tool names to their cost per query
	// +mapType=granular
	ToolNameToCostPerQuery map[string]*float64 `json:"toolNameToCostPerQuery,omitempty" tf:"tool_name_to_cost_per_query,omitempty"`
}

type McpServerCostInfoParameters struct {

	// Default cost per query for all tools.
	// Default cost per query
	// +kubebuilder:validation:Optional
	DefaultCostPerQuery *float64 `json:"defaultCostPerQuery,omitempty" tf:"default_cost_per_query,omitempty"`

	// Map of specific tool names to their cost per query.
	// Map of tool names to their cost per query
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ToolNameToCostPerQuery map[string]*float64 `json:"toolNameToCostPerQuery,omitempty" tf:"tool_name_to_cost_per_query,omitempty"`
}

type McpServerInitParameters struct {

	// Alias for the MCP server. Used for easier reference.
	// Alias for the MCP server
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// List of arguments for the command (stdio transport only). Do not pass secrets as arguments; args are shown in plans, stored unencrypted in state, and visible in the server's process list.
	// Arguments for the command (stdio transport)
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Authentication type. Valid values: none, bearer, basic. Defaults to none.
	// Authentication type (none, bearer, basic)
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// Command to run for stdio transport.
	// Command to run for stdio transport
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Description of the MCP server.
	// Description of the MCP server
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Env map[string]*string `json:"envSecretRef,omitempty" tf:"-"`

	// List of access groups that can use this MCP server.
	// List of access groups for the MCP server
	McpAccessGroups []*string `json:"mcpAccessGroups,omitempty" tf:"mcp_access_groups,omitempty"`

	// MCP server information and configuration
	McpInfo []McpInfoInitParameters `json:"mcpInfo,omitempty" tf:"mcp_info,omitempty"`

	// Name of the MCP server.
	// Name of the MCP server
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	// MCP specification version. Defaults to 2024-11-05.
	// MCP specification version
	SpecVersion *string `json:"specVersion,omitempty" tf:"spec_version,omitempty"`

	// Transport type for the MCP server. Valid values: http, sse, stdio.
	// Transport type for the MCP server (http, sse, stdio)
	Transport *string `json:"transport,omitempty" tf:"transport,omitempty"`

	// URL of the MCP server. For stdio transport, use stdio:// prefix.
	// URL of the MCP server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type McpServerObservation struct {

	// Alias for the MCP server. Used for easier reference.
	// Alias for the MCP server
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// List of arguments for the command (stdio transport only). Do not pass secrets as arguments; args are shown in plans, stored unencrypted in state, and visible in the server's process list.
	// Arguments for the command (stdio transport)
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Authentication type. Valid values: none, bearer, basic. Defaults to none.
	// Authentication type (none, bearer, basic)
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// Command to run for stdio transport.
	// Command to run for stdio transport
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Timestamp when the server was created.
	// Timestamp when the server was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// User who created the server.
	// User who created the server
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Description of the MCP server.
	// Description of the MCP server
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Error message from the last health check, if any.
	// Error message from the last health check, if any
	HealthCheckError *string `json:"healthCheckError,omitempty" tf:"health_check_error,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Timestamp of the last health check.
	// Timestamp of the last health check
	LastHealthCheck *string `json:"lastHealthCheck,omitempty" tf:"last_health_check,omitempty"`

	// List of access groups that can use this MCP server.
	// List of access groups for the MCP server
	McpAccessGroups []*string `json:"mcpAccessGroups,omitempty" tf:"mcp_access_groups,omitempty"`

	// MCP server information and configuration
	McpInfo []McpInfoObservation `json:"mcpInfo,omitempty" tf:"mcp_info,omitempty"`

	// Unique identifier for the MCP server.
	// Unique identifier for the MCP server
	ServerID *string `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Name of the MCP server.
	// Name of the MCP server
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	// MCP specification version. Defaults to 2024-11-05.
	// MCP specification version
	SpecVersion *string `json:"specVersion,omitempty" tf:"spec_version,omitempty"`

	// Current status of the MCP server.
	// Current status of the MCP server
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Transport type for the MCP server. Valid values: http, sse, stdio.
	// Transport type for the MCP server (http, sse, stdio)
	Transport *string `json:"transport,omitempty" tf:"transport,omitempty"`

	// URL of the MCP server. For stdio transport, use stdio:// prefix.
	// URL of the MCP server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Timestamp when the server was last updated.
	// Timestamp when the server was last updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// User who last updated the server.
	// User who last updated the server
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`
}

type McpServerParameters struct {

	// Alias for the MCP server. Used for easier reference.
	// Alias for the MCP server
	// +kubebuilder:validation:Optional
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// List of arguments for the command (stdio transport only). Do not pass secrets as arguments; args are shown in plans, stored unencrypted in state, and visible in the server's process list.
	// Arguments for the command (stdio transport)
	// +kubebuilder:validation:Optional
	Args []*string `json:"args,omitempty" tf:"args,omitempty"`

	// Authentication type. Valid values: none, bearer, basic. Defaults to none.
	// Authentication type (none, bearer, basic)
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// Command to run for stdio transport.
	// Command to run for stdio transport
	// +kubebuilder:validation:Optional
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Description of the MCP server.
	// Description of the MCP server
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Map of environment variables for the command (stdio transport only). Hidden from plan output but still stored unencrypted in state; secure your state backend when configuring tokens here.
	// Environment variables for the command (stdio transport)
	// +kubebuilder:validation:Optional
	EnvSecretRef *v1.SecretReference `json:"envSecretRef,omitempty" tf:"-"`

	// List of access groups that can use this MCP server.
	// List of access groups for the MCP server
	// +kubebuilder:validation:Optional
	McpAccessGroups []*string `json:"mcpAccessGroups,omitempty" tf:"mcp_access_groups,omitempty"`

	// MCP server information and configuration
	// +kubebuilder:validation:Optional
	McpInfo []McpInfoParameters `json:"mcpInfo,omitempty" tf:"mcp_info,omitempty"`

	// Name of the MCP server.
	// Name of the MCP server
	// +kubebuilder:validation:Optional
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	// MCP specification version. Defaults to 2024-11-05.
	// MCP specification version
	// +kubebuilder:validation:Optional
	SpecVersion *string `json:"specVersion,omitempty" tf:"spec_version,omitempty"`

	// Transport type for the MCP server. Valid values: http, sse, stdio.
	// Transport type for the MCP server (http, sse, stdio)
	// +kubebuilder:validation:Optional
	Transport *string `json:"transport,omitempty" tf:"transport,omitempty"`

	// URL of the MCP server. For stdio transport, use stdio:// prefix.
	// URL of the MCP server
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// McpServerSpec defines the desired state of McpServer
type McpServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     McpServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider McpServerInitParameters `json:"initProvider,omitempty"`
}

// McpServerStatus defines the observed state of McpServer.
type McpServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        McpServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// McpServer is the Schema for the McpServers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type McpServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverName) || (has(self.initProvider) && has(self.initProvider.serverName))",message="spec.forProvider.serverName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.transport) || (has(self.initProvider) && has(self.initProvider.transport))",message="spec.forProvider.transport is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   McpServerSpec   `json:"spec"`
	Status McpServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// McpServerList contains a list of McpServers
type McpServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []McpServer `json:"items"`
}

// Repository type metadata.
var (
	McpServer_Kind             = "McpServer"
	McpServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: McpServer_Kind}.String()
	McpServer_KindAPIVersion   = McpServer_Kind + "." + CRDGroupVersion.String()
	McpServer_GroupVersionKind = CRDGroupVersion.WithKind(McpServer_Kind)
)

func init() {
	SchemeBuilder.Register(&McpServer{}, &McpServerList{})
}
