/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ModelInitParameters struct {

	// string. The API version to use for the model provider.
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// map(string). A map of arbitrary additional parameters that will be merged into the litellm_params object sent to the LiteLLM API. This is intended for provider-specific or experimental options not exposed as dedicated arguments.
	// Additional parameters to pass to litellm_params beyond the standard ones
	// +mapType=granular
	AdditionalLitellmParams map[string]*string `json:"additionalLitellmParams,omitempty" tf:"additional_litellm_params,omitempty"`

	// string (Sensitive). AWS access key ID for AWS-based models.
	AwsAccessKeyIDSecretRef *v1.SecretKeySelector `json:"awsAccessKeyIdSecretRef,omitempty" tf:"-"`

	// string. AWS region name for AWS-based models.
	AwsRegionName *string `json:"awsRegionName,omitempty" tf:"aws_region_name,omitempty"`

	// string (Sensitive). AWS IAM role name for cross-account access scenarios.
	AwsRoleNameSecretRef *v1.SecretKeySelector `json:"awsRoleNameSecretRef,omitempty" tf:"-"`

	// string (Sensitive). AWS secret access key for AWS-based models. As with model_api_key, the value is stored in plaintext in the state file; prefer a litellm_credential referenced via litellm_credential_name and secure your state backend.
	AwsSecretAccessKeySecretRef *v1.SecretKeySelector `json:"awsSecretAccessKeySecretRef,omitempty" tf:"-"`

	// string (Sensitive). AWS session name for cross-account access scenarios.
	AwsSessionNameSecretRef *v1.SecretKeySelector `json:"awsSessionNameSecretRef,omitempty" tf:"-"`

	// string. The actual model identifier from the provider (e.g., "gpt-4", "claude-2").
	BaseModel *string `json:"baseModel,omitempty" tf:"base_model,omitempty"`

	// string. The LLM provider for this model (e.g., "openai", "anthropic", "azure", "bedrock").
	CustomLlmProvider *string `json:"customLlmProvider,omitempty" tf:"custom_llm_provider,omitempty"`

	// float. Cost per million input tokens. The provider converts this to a per-token cost sent to the API.
	InputCostPerMillionTokens *float64 `json:"inputCostPerMillionTokens,omitempty" tf:"input_cost_per_million_tokens,omitempty"`

	// float. Cost applied per input pixel for models that charge by image size.
	InputCostPerPixel *float64 `json:"inputCostPerPixel,omitempty" tf:"input_cost_per_pixel,omitempty"`

	// float. Cost applied per input second for audio/transcription models.
	InputCostPerSecond *float64 `json:"inputCostPerSecond,omitempty" tf:"input_cost_per_second,omitempty"`

	// string. Name of a LiteLLM credential to use for this model.
	// Name of the LiteLLM credential to use
	LitellmCredentialName *string `json:"litellmCredentialName,omitempty" tf:"litellm_credential_name,omitempty"`

	// boolean. When set to true, merges reasoning content into the model's choices.
	MergeReasoningContentInChoices *bool `json:"mergeReasoningContentInChoices,omitempty" tf:"merge_reasoning_content_in_choices,omitempty"`

	// string. The intended use of the model. Valid values are:
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// string. The base URL for the model provider's API.
	ModelAPIBase *string `json:"modelApiBase,omitempty" tf:"model_api_base,omitempty"`

	// string (Sensitive). The API key for the underlying model provider.
	ModelAPIKeySecretRef *v1.SecretKeySelector `json:"modelApiKeySecretRef,omitempty" tf:"-"`

	// string. The name of the model configuration used to identify the model in API calls.
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`

	// float. Cost per million output tokens. The provider converts this to a per-token cost sent to the API.
	OutputCostPerMillionTokens *float64 `json:"outputCostPerMillionTokens,omitempty" tf:"output_cost_per_million_tokens,omitempty"`

	// float. Cost applied per output pixel for image-generation models.
	OutputCostPerPixel *float64 `json:"outputCostPerPixel,omitempty" tf:"output_cost_per_pixel,omitempty"`

	// float. Cost applied per output second for audio/transcription models.
	OutputCostPerSecond *float64 `json:"outputCostPerSecond,omitempty" tf:"output_cost_per_second,omitempty"`

	// string. A pricing key fed to model_info.base_model independently of routing. When set, litellm_params.model still routes via base_model, but LiteLLM looks up cost against this key. Useful when the routing/deployment name differs from the cost-map key — e.g. an Azure deployment routed as azure/gpt-4.1 whose real tier is Data Zone: set pricing_base_model = "us/gpt-4.1-2025-04-14" so it is billed at the Data Zone rate. When unset, base_model drives pricing as before.
	PricingBaseModel *string `json:"pricingBaseModel,omitempty" tf:"pricing_base_model,omitempty"`

	// string. Configures the model's reasoning effort level. Valid values are:
	ReasoningEffort *string `json:"reasoningEffort,omitempty" tf:"reasoning_effort,omitempty"`

	// integer. Requests per minute limit for this model.
	Rpm *float64 `json:"rpm,omitempty" tf:"rpm,omitempty"`

	// string. Associate the model with a specific team.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// integer. Sets the token budget for the model's thinking capability. Default: 1024. Note: this field is only relevant when thinking_enabled = true.
	ThinkingBudgetTokens *float64 `json:"thinkingBudgetTokens,omitempty" tf:"thinking_budget_tokens,omitempty"`

	// boolean. Enables the model's thinking capability. Default: false.
	ThinkingEnabled *bool `json:"thinkingEnabled,omitempty" tf:"thinking_enabled,omitempty"`

	// string. The usage tier for this model. Valid values are "free" or "paid". Default: "free".
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// integer. Tokens per minute limit for this model.
	Tpm *float64 `json:"tpm,omitempty" tf:"tpm,omitempty"`

	// string. Vertex credentials (JSON string or path depending on your setup).
	VertexCredentialsSecretRef *v1.SecretKeySelector `json:"vertexCredentialsSecretRef,omitempty" tf:"-"`

	// string. Vertex AI location (e.g., us-central1).
	VertexLocationSecretRef *v1.SecretKeySelector `json:"vertexLocationSecretRef,omitempty" tf:"-"`

	// string. Vertex AI project id (for custom_llm_provider = "vertex").
	VertexProjectSecretRef *v1.SecretKeySelector `json:"vertexProjectSecretRef,omitempty" tf:"-"`
}

type ModelObservation struct {

	// string. The API version to use for the model provider.
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// map(string). A map of arbitrary additional parameters that will be merged into the litellm_params object sent to the LiteLLM API. This is intended for provider-specific or experimental options not exposed as dedicated arguments.
	// Additional parameters to pass to litellm_params beyond the standard ones
	// +mapType=granular
	AdditionalLitellmParams map[string]*string `json:"additionalLitellmParams,omitempty" tf:"additional_litellm_params,omitempty"`

	// string. AWS region name for AWS-based models.
	AwsRegionName *string `json:"awsRegionName,omitempty" tf:"aws_region_name,omitempty"`

	// string. The actual model identifier from the provider (e.g., "gpt-4", "claude-2").
	BaseModel *string `json:"baseModel,omitempty" tf:"base_model,omitempty"`

	// string. The LLM provider for this model (e.g., "openai", "anthropic", "azure", "bedrock").
	CustomLlmProvider *string `json:"customLlmProvider,omitempty" tf:"custom_llm_provider,omitempty"`

	// The ID of the model configuration.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// float. Cost per million input tokens. The provider converts this to a per-token cost sent to the API.
	InputCostPerMillionTokens *float64 `json:"inputCostPerMillionTokens,omitempty" tf:"input_cost_per_million_tokens,omitempty"`

	// float. Cost applied per input pixel for models that charge by image size.
	InputCostPerPixel *float64 `json:"inputCostPerPixel,omitempty" tf:"input_cost_per_pixel,omitempty"`

	// float. Cost applied per input second for audio/transcription models.
	InputCostPerSecond *float64 `json:"inputCostPerSecond,omitempty" tf:"input_cost_per_second,omitempty"`

	// string. Name of a LiteLLM credential to use for this model.
	// Name of the LiteLLM credential to use
	LitellmCredentialName *string `json:"litellmCredentialName,omitempty" tf:"litellm_credential_name,omitempty"`

	// boolean. When set to true, merges reasoning content into the model's choices.
	MergeReasoningContentInChoices *bool `json:"mergeReasoningContentInChoices,omitempty" tf:"merge_reasoning_content_in_choices,omitempty"`

	// string. The intended use of the model. Valid values are:
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// string. The base URL for the model provider's API.
	ModelAPIBase *string `json:"modelApiBase,omitempty" tf:"model_api_base,omitempty"`

	// string. The name of the model configuration used to identify the model in API calls.
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`

	// float. Cost per million output tokens. The provider converts this to a per-token cost sent to the API.
	OutputCostPerMillionTokens *float64 `json:"outputCostPerMillionTokens,omitempty" tf:"output_cost_per_million_tokens,omitempty"`

	// float. Cost applied per output pixel for image-generation models.
	OutputCostPerPixel *float64 `json:"outputCostPerPixel,omitempty" tf:"output_cost_per_pixel,omitempty"`

	// float. Cost applied per output second for audio/transcription models.
	OutputCostPerSecond *float64 `json:"outputCostPerSecond,omitempty" tf:"output_cost_per_second,omitempty"`

	// string. A pricing key fed to model_info.base_model independently of routing. When set, litellm_params.model still routes via base_model, but LiteLLM looks up cost against this key. Useful when the routing/deployment name differs from the cost-map key — e.g. an Azure deployment routed as azure/gpt-4.1 whose real tier is Data Zone: set pricing_base_model = "us/gpt-4.1-2025-04-14" so it is billed at the Data Zone rate. When unset, base_model drives pricing as before.
	PricingBaseModel *string `json:"pricingBaseModel,omitempty" tf:"pricing_base_model,omitempty"`

	// string. Configures the model's reasoning effort level. Valid values are:
	ReasoningEffort *string `json:"reasoningEffort,omitempty" tf:"reasoning_effort,omitempty"`

	// integer. Requests per minute limit for this model.
	Rpm *float64 `json:"rpm,omitempty" tf:"rpm,omitempty"`

	// string. Associate the model with a specific team.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// integer. Sets the token budget for the model's thinking capability. Default: 1024. Note: this field is only relevant when thinking_enabled = true.
	ThinkingBudgetTokens *float64 `json:"thinkingBudgetTokens,omitempty" tf:"thinking_budget_tokens,omitempty"`

	// boolean. Enables the model's thinking capability. Default: false.
	ThinkingEnabled *bool `json:"thinkingEnabled,omitempty" tf:"thinking_enabled,omitempty"`

	// string. The usage tier for this model. Valid values are "free" or "paid". Default: "free".
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// integer. Tokens per minute limit for this model.
	Tpm *float64 `json:"tpm,omitempty" tf:"tpm,omitempty"`
}

type ModelParameters struct {

	// string. The API version to use for the model provider.
	// +kubebuilder:validation:Optional
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// map(string). A map of arbitrary additional parameters that will be merged into the litellm_params object sent to the LiteLLM API. This is intended for provider-specific or experimental options not exposed as dedicated arguments.
	// Additional parameters to pass to litellm_params beyond the standard ones
	// +kubebuilder:validation:Optional
	// +mapType=granular
	AdditionalLitellmParams map[string]*string `json:"additionalLitellmParams,omitempty" tf:"additional_litellm_params,omitempty"`

	// string (Sensitive). AWS access key ID for AWS-based models.
	// +kubebuilder:validation:Optional
	AwsAccessKeyIDSecretRef *v1.SecretKeySelector `json:"awsAccessKeyIdSecretRef,omitempty" tf:"-"`

	// string. AWS region name for AWS-based models.
	// +kubebuilder:validation:Optional
	AwsRegionName *string `json:"awsRegionName,omitempty" tf:"aws_region_name,omitempty"`

	// string (Sensitive). AWS IAM role name for cross-account access scenarios.
	// +kubebuilder:validation:Optional
	AwsRoleNameSecretRef *v1.SecretKeySelector `json:"awsRoleNameSecretRef,omitempty" tf:"-"`

	// string (Sensitive). AWS secret access key for AWS-based models. As with model_api_key, the value is stored in plaintext in the state file; prefer a litellm_credential referenced via litellm_credential_name and secure your state backend.
	// +kubebuilder:validation:Optional
	AwsSecretAccessKeySecretRef *v1.SecretKeySelector `json:"awsSecretAccessKeySecretRef,omitempty" tf:"-"`

	// string (Sensitive). AWS session name for cross-account access scenarios.
	// +kubebuilder:validation:Optional
	AwsSessionNameSecretRef *v1.SecretKeySelector `json:"awsSessionNameSecretRef,omitempty" tf:"-"`

	// string. The actual model identifier from the provider (e.g., "gpt-4", "claude-2").
	// +kubebuilder:validation:Optional
	BaseModel *string `json:"baseModel,omitempty" tf:"base_model,omitempty"`

	// string. The LLM provider for this model (e.g., "openai", "anthropic", "azure", "bedrock").
	// +kubebuilder:validation:Optional
	CustomLlmProvider *string `json:"customLlmProvider,omitempty" tf:"custom_llm_provider,omitempty"`

	// float. Cost per million input tokens. The provider converts this to a per-token cost sent to the API.
	// +kubebuilder:validation:Optional
	InputCostPerMillionTokens *float64 `json:"inputCostPerMillionTokens,omitempty" tf:"input_cost_per_million_tokens,omitempty"`

	// float. Cost applied per input pixel for models that charge by image size.
	// +kubebuilder:validation:Optional
	InputCostPerPixel *float64 `json:"inputCostPerPixel,omitempty" tf:"input_cost_per_pixel,omitempty"`

	// float. Cost applied per input second for audio/transcription models.
	// +kubebuilder:validation:Optional
	InputCostPerSecond *float64 `json:"inputCostPerSecond,omitempty" tf:"input_cost_per_second,omitempty"`

	// string. Name of a LiteLLM credential to use for this model.
	// Name of the LiteLLM credential to use
	// +kubebuilder:validation:Optional
	LitellmCredentialName *string `json:"litellmCredentialName,omitempty" tf:"litellm_credential_name,omitempty"`

	// boolean. When set to true, merges reasoning content into the model's choices.
	// +kubebuilder:validation:Optional
	MergeReasoningContentInChoices *bool `json:"mergeReasoningContentInChoices,omitempty" tf:"merge_reasoning_content_in_choices,omitempty"`

	// string. The intended use of the model. Valid values are:
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// string. The base URL for the model provider's API.
	// +kubebuilder:validation:Optional
	ModelAPIBase *string `json:"modelApiBase,omitempty" tf:"model_api_base,omitempty"`

	// string (Sensitive). The API key for the underlying model provider.
	// +kubebuilder:validation:Optional
	ModelAPIKeySecretRef *v1.SecretKeySelector `json:"modelApiKeySecretRef,omitempty" tf:"-"`

	// string. The name of the model configuration used to identify the model in API calls.
	// +kubebuilder:validation:Optional
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`

	// float. Cost per million output tokens. The provider converts this to a per-token cost sent to the API.
	// +kubebuilder:validation:Optional
	OutputCostPerMillionTokens *float64 `json:"outputCostPerMillionTokens,omitempty" tf:"output_cost_per_million_tokens,omitempty"`

	// float. Cost applied per output pixel for image-generation models.
	// +kubebuilder:validation:Optional
	OutputCostPerPixel *float64 `json:"outputCostPerPixel,omitempty" tf:"output_cost_per_pixel,omitempty"`

	// float. Cost applied per output second for audio/transcription models.
	// +kubebuilder:validation:Optional
	OutputCostPerSecond *float64 `json:"outputCostPerSecond,omitempty" tf:"output_cost_per_second,omitempty"`

	// string. A pricing key fed to model_info.base_model independently of routing. When set, litellm_params.model still routes via base_model, but LiteLLM looks up cost against this key. Useful when the routing/deployment name differs from the cost-map key — e.g. an Azure deployment routed as azure/gpt-4.1 whose real tier is Data Zone: set pricing_base_model = "us/gpt-4.1-2025-04-14" so it is billed at the Data Zone rate. When unset, base_model drives pricing as before.
	// +kubebuilder:validation:Optional
	PricingBaseModel *string `json:"pricingBaseModel,omitempty" tf:"pricing_base_model,omitempty"`

	// string. Configures the model's reasoning effort level. Valid values are:
	// +kubebuilder:validation:Optional
	ReasoningEffort *string `json:"reasoningEffort,omitempty" tf:"reasoning_effort,omitempty"`

	// integer. Requests per minute limit for this model.
	// +kubebuilder:validation:Optional
	Rpm *float64 `json:"rpm,omitempty" tf:"rpm,omitempty"`

	// string. Associate the model with a specific team.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// integer. Sets the token budget for the model's thinking capability. Default: 1024. Note: this field is only relevant when thinking_enabled = true.
	// +kubebuilder:validation:Optional
	ThinkingBudgetTokens *float64 `json:"thinkingBudgetTokens,omitempty" tf:"thinking_budget_tokens,omitempty"`

	// boolean. Enables the model's thinking capability. Default: false.
	// +kubebuilder:validation:Optional
	ThinkingEnabled *bool `json:"thinkingEnabled,omitempty" tf:"thinking_enabled,omitempty"`

	// string. The usage tier for this model. Valid values are "free" or "paid". Default: "free".
	// +kubebuilder:validation:Optional
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// integer. Tokens per minute limit for this model.
	// +kubebuilder:validation:Optional
	Tpm *float64 `json:"tpm,omitempty" tf:"tpm,omitempty"`

	// string. Vertex credentials (JSON string or path depending on your setup).
	// +kubebuilder:validation:Optional
	VertexCredentialsSecretRef *v1.SecretKeySelector `json:"vertexCredentialsSecretRef,omitempty" tf:"-"`

	// string. Vertex AI location (e.g., us-central1).
	// +kubebuilder:validation:Optional
	VertexLocationSecretRef *v1.SecretKeySelector `json:"vertexLocationSecretRef,omitempty" tf:"-"`

	// string. Vertex AI project id (for custom_llm_provider = "vertex").
	// +kubebuilder:validation:Optional
	VertexProjectSecretRef *v1.SecretKeySelector `json:"vertexProjectSecretRef,omitempty" tf:"-"`
}

// ModelSpec defines the desired state of Model
type ModelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ModelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ModelInitParameters `json:"initProvider,omitempty"`
}

// ModelStatus defines the observed state of Model.
type ModelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ModelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Model is the Schema for the Models API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Model struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.baseModel) || (has(self.initProvider) && has(self.initProvider.baseModel))",message="spec.forProvider.baseModel is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.customLlmProvider) || (has(self.initProvider) && has(self.initProvider.customLlmProvider))",message="spec.forProvider.customLlmProvider is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.modelName) || (has(self.initProvider) && has(self.initProvider.modelName))",message="spec.forProvider.modelName is a required parameter"
	Spec   ModelSpec   `json:"spec"`
	Status ModelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ModelList contains a list of Models
type ModelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Model `json:"items"`
}

// Repository type metadata.
var (
	Model_Kind             = "Model"
	Model_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Model_Kind}.String()
	Model_KindAPIVersion   = Model_Kind + "." + CRDGroupVersion.String()
	Model_GroupVersionKind = CRDGroupVersion.WithKind(Model_Kind)
)

func init() {
	SchemeBuilder.Register(&Model{}, &ModelList{})
}
