/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MemberInitParameters struct {
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type MemberObservation struct {
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type MemberParameters struct {

	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`

	// +kubebuilder:validation:Optional
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type OrganizationMemberAddInitParameters struct {
	Member []MemberInitParameters `json:"member,omitempty" tf:"member,omitempty"`

	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type OrganizationMemberAddObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Member []MemberObservation `json:"member,omitempty" tf:"member,omitempty"`

	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type OrganizationMemberAddParameters struct {

	// +kubebuilder:validation:Optional
	Member []MemberParameters `json:"member,omitempty" tf:"member,omitempty"`

	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

// OrganizationMemberAddSpec defines the desired state of OrganizationMemberAdd
type OrganizationMemberAddSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OrganizationMemberAddParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationMemberAddInitParameters `json:"initProvider,omitempty"`
}

// OrganizationMemberAddStatus defines the observed state of OrganizationMemberAdd.
type OrganizationMemberAddStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrganizationMemberAddObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationMemberAdd is the Schema for the OrganizationMemberAdds API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type OrganizationMemberAdd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organizationId) || (has(self.initProvider) && has(self.initProvider.organizationId))",message="spec.forProvider.organizationId is a required parameter"
	Spec   OrganizationMemberAddSpec   `json:"spec"`
	Status OrganizationMemberAddStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationMemberAddList contains a list of OrganizationMemberAdds
type OrganizationMemberAddList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationMemberAdd `json:"items"`
}

// Repository type metadata.
var (
	OrganizationMemberAdd_Kind             = "OrganizationMemberAdd"
	OrganizationMemberAdd_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationMemberAdd_Kind}.String()
	OrganizationMemberAdd_KindAPIVersion   = OrganizationMemberAdd_Kind + "." + CRDGroupVersion.String()
	OrganizationMemberAdd_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationMemberAdd_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationMemberAdd{}, &OrganizationMemberAddList{})
}
