/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TeamMemberAddInitParameters struct {

	// List of models each team member can access. If not set, members inherit the team's default_team_member_models or all team models.
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`

	// Duration after which each member's budget resets, for example "1h", "24h", "7d", "30d". If not set, the budget never resets.
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// The maximum budget allocated for the team members.
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// One or more member blocks defining team members. Each block supports:
	Member []TeamMemberAddMemberInitParameters `json:"member,omitempty" tf:"member,omitempty"`

	// Requests per minute limit applied to each team member. Sent via /team/member_update after members are added, since /team/member_add does not accept it.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// The ID of the team to add members to.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit applied to each team member. Sent via /team/member_update after members are added, since /team/member_add does not accept it.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

type TeamMemberAddMemberInitParameters struct {

	// The role of the user in the team. Must be one of: "admin" or "user".
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The email of the user to add to the team.
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// The ID of the user to add to the team.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMemberAddMemberObservation struct {

	// The role of the user in the team. Must be one of: "admin" or "user".
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The email of the user to add to the team.
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// The ID of the user to add to the team.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMemberAddMemberParameters struct {

	// The role of the user in the team. Must be one of: "admin" or "user".
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`

	// The email of the user to add to the team.
	// +kubebuilder:validation:Optional
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// The ID of the user to add to the team.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMemberAddObservation struct {

	// List of models each team member can access. If not set, members inherit the team's default_team_member_models or all team models.
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`

	// Duration after which each member's budget resets, for example "1h", "24h", "7d", "30d". If not set, the budget never resets.
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The maximum budget allocated for the team members.
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// One or more member blocks defining team members. Each block supports:
	Member []TeamMemberAddMemberObservation `json:"member,omitempty" tf:"member,omitempty"`

	// Requests per minute limit applied to each team member. Sent via /team/member_update after members are added, since /team/member_add does not accept it.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// The ID of the team to add members to.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit applied to each team member. Sent via /team/member_update after members are added, since /team/member_add does not accept it.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

type TeamMemberAddParameters struct {

	// List of models each team member can access. If not set, members inherit the team's default_team_member_models or all team models.
	// +kubebuilder:validation:Optional
	AllowedModels []*string `json:"allowedModels,omitempty" tf:"allowed_models,omitempty"`

	// Duration after which each member's budget resets, for example "1h", "24h", "7d", "30d". If not set, the budget never resets.
	// +kubebuilder:validation:Optional
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// The maximum budget allocated for the team members.
	// +kubebuilder:validation:Optional
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// One or more member blocks defining team members. Each block supports:
	// +kubebuilder:validation:Optional
	Member []TeamMemberAddMemberParameters `json:"member,omitempty" tf:"member,omitempty"`

	// Requests per minute limit applied to each team member. Sent via /team/member_update after members are added, since /team/member_add does not accept it.
	// +kubebuilder:validation:Optional
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// The ID of the team to add members to.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit applied to each team member. Sent via /team/member_update after members are added, since /team/member_add does not accept it.
	// +kubebuilder:validation:Optional
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

// TeamMemberAddSpec defines the desired state of TeamMemberAdd
type TeamMemberAddSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamMemberAddParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamMemberAddInitParameters `json:"initProvider,omitempty"`
}

// TeamMemberAddStatus defines the observed state of TeamMemberAdd.
type TeamMemberAddStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamMemberAddObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamMemberAdd is the Schema for the TeamMemberAdds API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type TeamMemberAdd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.teamId) || (has(self.initProvider) && has(self.initProvider.teamId))",message="spec.forProvider.teamId is a required parameter"
	Spec   TeamMemberAddSpec   `json:"spec"`
	Status TeamMemberAddStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamMemberAddList contains a list of TeamMemberAdds
type TeamMemberAddList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamMemberAdd `json:"items"`
}

// Repository type metadata.
var (
	TeamMemberAdd_Kind             = "TeamMemberAdd"
	TeamMemberAdd_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamMemberAdd_Kind}.String()
	TeamMemberAdd_KindAPIVersion   = TeamMemberAdd_Kind + "." + CRDGroupVersion.String()
	TeamMemberAdd_GroupVersionKind = CRDGroupVersion.WithKind(TeamMemberAdd_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamMemberAdd{}, &TeamMemberAddList{})
}
