/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TeamMemberInitParameters struct {

	// Maximum budget allocated to this team member within the team's budget.
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// The role of the team member. Valid values are:
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The ID of the team this member belongs to.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Email address of the user.
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// Unique identifier for the user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMemberObservation struct {

	// The unique identifier for the team member configuration. This is typically a composite of the team_id and user_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Maximum budget allocated to this team member within the team's budget.
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// The role of the team member. Valid values are:
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The ID of the team this member belongs to.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Email address of the user.
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// Unique identifier for the user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMemberParameters struct {

	// Maximum budget allocated to this team member within the team's budget.
	// +kubebuilder:validation:Optional
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// The role of the team member. Valid values are:
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The ID of the team this member belongs to.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Email address of the user.
	// +kubebuilder:validation:Optional
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// Unique identifier for the user.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// TeamMemberSpec defines the desired state of TeamMember
type TeamMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamMemberInitParameters `json:"initProvider,omitempty"`
}

// TeamMemberStatus defines the observed state of TeamMember.
type TeamMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamMember is the Schema for the TeamMembers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type TeamMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.teamId) || (has(self.initProvider) && has(self.initProvider.teamId))",message="spec.forProvider.teamId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userEmail) || (has(self.initProvider) && has(self.initProvider.userEmail))",message="spec.forProvider.userEmail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userId) || (has(self.initProvider) && has(self.initProvider.userId))",message="spec.forProvider.userId is a required parameter"
	Spec   TeamMemberSpec   `json:"spec"`
	Status TeamMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamMemberList contains a list of TeamMembers
type TeamMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamMember `json:"items"`
}

// Repository type metadata.
var (
	TeamMember_Kind             = "TeamMember"
	TeamMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamMember_Kind}.String()
	TeamMember_KindAPIVersion   = TeamMember_Kind + "." + CRDGroupVersion.String()
	TeamMember_GroupVersionKind = CRDGroupVersion.WithKind(TeamMember_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamMember{}, &TeamMemberList{})
}
