/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TeamInitParameters struct {

	// Whether the team is blocked from making requests. Default is false.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget cycle. Valid values are:
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Maximum budget allocated to the team.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// A map of metadata key-value pairs associated with the team.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// List of model names that this team can access.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// The ID of the organization this team belongs to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Team-wide requests per minute limit.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// A human-readable identifier for the team.
	TeamAlias *string `json:"teamAlias,omitempty" tf:"team_alias,omitempty"`

	// List of permissions granted to team members. This controls what actions team members can perform within the team context.
	// List of permissions granted to team members
	TeamMemberPermissions []*string `json:"teamMemberPermissions,omitempty" tf:"team_member_permissions,omitempty"`

	// Team-wide tokens per minute limit.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

type TeamObservation struct {

	// Whether the team is blocked from making requests. Default is false.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget cycle. Valid values are:
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// The unique identifier for the team.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Maximum budget allocated to the team.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// A map of metadata key-value pairs associated with the team.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// List of model names that this team can access.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// The ID of the organization this team belongs to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Team-wide requests per minute limit.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// A human-readable identifier for the team.
	TeamAlias *string `json:"teamAlias,omitempty" tf:"team_alias,omitempty"`

	// List of permissions granted to team members. This controls what actions team members can perform within the team context.
	// List of permissions granted to team members
	TeamMemberPermissions []*string `json:"teamMemberPermissions,omitempty" tf:"team_member_permissions,omitempty"`

	// Team-wide tokens per minute limit.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

type TeamParameters struct {

	// Whether the team is blocked from making requests. Default is false.
	// +kubebuilder:validation:Optional
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget cycle. Valid values are:
	// +kubebuilder:validation:Optional
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Maximum budget allocated to the team.
	// +kubebuilder:validation:Optional
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// A map of metadata key-value pairs associated with the team.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// List of model names that this team can access.
	// +kubebuilder:validation:Optional
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// The ID of the organization this team belongs to.
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Team-wide requests per minute limit.
	// +kubebuilder:validation:Optional
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// A human-readable identifier for the team.
	// +kubebuilder:validation:Optional
	TeamAlias *string `json:"teamAlias,omitempty" tf:"team_alias,omitempty"`

	// List of permissions granted to team members. This controls what actions team members can perform within the team context.
	// List of permissions granted to team members
	// +kubebuilder:validation:Optional
	TeamMemberPermissions []*string `json:"teamMemberPermissions,omitempty" tf:"team_member_permissions,omitempty"`

	// Team-wide tokens per minute limit.
	// +kubebuilder:validation:Optional
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

// TeamSpec defines the desired state of Team
type TeamSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamInitParameters `json:"initProvider,omitempty"`
}

// TeamStatus defines the observed state of Team.
type TeamStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Team is the Schema for the Teams API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Team struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.teamAlias) || (has(self.initProvider) && has(self.initProvider.teamAlias))",message="spec.forProvider.teamAlias is a required parameter"
	Spec   TeamSpec   `json:"spec"`
	Status TeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamList contains a list of Teams
type TeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Team `json:"items"`
}

// Repository type metadata.
var (
	Team_Kind             = "Team"
	Team_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Team_Kind}.String()
	Team_KindAPIVersion   = Team_Kind + "." + CRDGroupVersion.String()
	Team_GroupVersionKind = CRDGroupVersion.WithKind(Team_Kind)
)

func init() {
	SchemeBuilder.Register(&Team{}, &TeamList{})
}
