/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TeamInitParameters struct {

	// List of pass-through routes this team is allowed to call.
	AllowedPassthroughRoutes []*string `json:"allowedPassthroughRoutes,omitempty" tf:"allowed_passthrough_routes,omitempty"`

	// Whether the team is blocked from making requests. Default is false.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget cycle. Valid values are:
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// List of guardrails applied to every request made by this team.
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Maximum budget allocated to the team.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// A map of string metadata key-value pairs associated with the team. tags and soft_budget_alerting_emails are stored by the proxy under metadata but are managed through their own attributes below, not this map.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Map of alias names to model names, letting the team call models under stable alias names.
	// +mapType=granular
	ModelAliases map[string]*string `json:"modelAliases,omitempty" tf:"model_aliases,omitempty"`

	// Map of model name to requests per minute limit for that model.
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Map of model name to tokens per minute limit for that model.
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of model names that this team can access.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// The ID of the organization this team belongs to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// List of prompt IDs the team is allowed to use.
	Prompts []*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// Team-wide requests per minute limit.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// How the RPM limit is enforced: guaranteed_throughput or best_effort_throughput. Changing this forces a new team to be created.
	// One of 'guaranteed_throughput' or 'best_effort_throughput'; only settable at creation
	RpmLimitType *string `json:"rpmLimitType,omitempty" tf:"rpm_limit_type,omitempty"`

	// Spend threshold at which the proxy sends a soft budget alert without blocking requests.
	// Spend threshold that triggers a soft budget alert without blocking requests
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// List of email addresses notified when the team's spend crosses soft_budget.
	// Email addresses alerted when the team crosses soft_budget
	SoftBudgetAlertingEmails []*string `json:"softBudgetAlertingEmails,omitempty" tf:"soft_budget_alerting_emails,omitempty"`

	// List of tags applied to the team, used for spend tracking and tag-based routing.
	// Tags for spend tracking and tag-based routing
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A human-readable identifier for the team.
	TeamAlias *string `json:"teamAlias,omitempty" tf:"team_alias,omitempty"`

	// A stable, human-readable ID for the team (for example platform-team). If omitted, the provider generates a random UUID. Changing this forces a new team to be created.
	// Unique ID for the team. Generated by the provider if not provided
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Budget (in USD) applied to each individual team member.
	// Budget applied to every team member
	TeamMemberBudget *float64 `json:"teamMemberBudget,omitempty" tf:"team_member_budget,omitempty"`

	// Reset cycle for the per-member budget (e.g. 30d, 1mo).
	TeamMemberBudgetDuration *string `json:"teamMemberBudgetDuration,omitempty" tf:"team_member_budget_duration,omitempty"`

	// Lifetime for keys created by team members (e.g. 1d, 1w).
	TeamMemberKeyDuration *string `json:"teamMemberKeyDuration,omitempty" tf:"team_member_key_duration,omitempty"`

	// List of permissions granted to team members. This controls what actions team members can perform within the team context.
	// List of permissions granted to team members
	TeamMemberPermissions []*string `json:"teamMemberPermissions,omitempty" tf:"team_member_permissions,omitempty"`

	// Requests per minute limit applied to each individual team member.
	TeamMemberRpmLimit *float64 `json:"teamMemberRpmLimit,omitempty" tf:"team_member_rpm_limit,omitempty"`

	// Tokens per minute limit applied to each individual team member.
	TeamMemberTpmLimit *float64 `json:"teamMemberTpmLimit,omitempty" tf:"team_member_tpm_limit,omitempty"`

	// Team-wide tokens per minute limit.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// How the TPM limit is enforced: guaranteed_throughput or best_effort_throughput. Changing this forces a new team to be created.
	// One of 'guaranteed_throughput' or 'best_effort_throughput'; only settable at creation
	TpmLimitType *string `json:"tpmLimitType,omitempty" tf:"tpm_limit_type,omitempty"`
}

type TeamObservation struct {

	// List of pass-through routes this team is allowed to call.
	AllowedPassthroughRoutes []*string `json:"allowedPassthroughRoutes,omitempty" tf:"allowed_passthrough_routes,omitempty"`

	// Whether the team is blocked from making requests. Default is false.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget cycle. Valid values are:
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// List of guardrails applied to every request made by this team.
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// The unique identifier for the team, equal to team_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Maximum budget allocated to the team.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// A map of string metadata key-value pairs associated with the team. tags and soft_budget_alerting_emails are stored by the proxy under metadata but are managed through their own attributes below, not this map.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Map of alias names to model names, letting the team call models under stable alias names.
	// +mapType=granular
	ModelAliases map[string]*string `json:"modelAliases,omitempty" tf:"model_aliases,omitempty"`

	// Map of model name to requests per minute limit for that model.
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Map of model name to tokens per minute limit for that model.
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of model names that this team can access.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// The ID of the organization this team belongs to.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// List of prompt IDs the team is allowed to use.
	Prompts []*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// Team-wide requests per minute limit.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// How the RPM limit is enforced: guaranteed_throughput or best_effort_throughput. Changing this forces a new team to be created.
	// One of 'guaranteed_throughput' or 'best_effort_throughput'; only settable at creation
	RpmLimitType *string `json:"rpmLimitType,omitempty" tf:"rpm_limit_type,omitempty"`

	// Spend threshold at which the proxy sends a soft budget alert without blocking requests.
	// Spend threshold that triggers a soft budget alert without blocking requests
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// List of email addresses notified when the team's spend crosses soft_budget.
	// Email addresses alerted when the team crosses soft_budget
	SoftBudgetAlertingEmails []*string `json:"softBudgetAlertingEmails,omitempty" tf:"soft_budget_alerting_emails,omitempty"`

	// List of tags applied to the team, used for spend tracking and tag-based routing.
	// Tags for spend tracking and tag-based routing
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A human-readable identifier for the team.
	TeamAlias *string `json:"teamAlias,omitempty" tf:"team_alias,omitempty"`

	// A stable, human-readable ID for the team (for example platform-team). If omitted, the provider generates a random UUID. Changing this forces a new team to be created.
	// Unique ID for the team. Generated by the provider if not provided
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Budget (in USD) applied to each individual team member.
	// Budget applied to every team member
	TeamMemberBudget *float64 `json:"teamMemberBudget,omitempty" tf:"team_member_budget,omitempty"`

	// Reset cycle for the per-member budget (e.g. 30d, 1mo).
	TeamMemberBudgetDuration *string `json:"teamMemberBudgetDuration,omitempty" tf:"team_member_budget_duration,omitempty"`

	// Lifetime for keys created by team members (e.g. 1d, 1w).
	TeamMemberKeyDuration *string `json:"teamMemberKeyDuration,omitempty" tf:"team_member_key_duration,omitempty"`

	// List of permissions granted to team members. This controls what actions team members can perform within the team context.
	// List of permissions granted to team members
	TeamMemberPermissions []*string `json:"teamMemberPermissions,omitempty" tf:"team_member_permissions,omitempty"`

	// Requests per minute limit applied to each individual team member.
	TeamMemberRpmLimit *float64 `json:"teamMemberRpmLimit,omitempty" tf:"team_member_rpm_limit,omitempty"`

	// Tokens per minute limit applied to each individual team member.
	TeamMemberTpmLimit *float64 `json:"teamMemberTpmLimit,omitempty" tf:"team_member_tpm_limit,omitempty"`

	// Team-wide tokens per minute limit.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// How the TPM limit is enforced: guaranteed_throughput or best_effort_throughput. Changing this forces a new team to be created.
	// One of 'guaranteed_throughput' or 'best_effort_throughput'; only settable at creation
	TpmLimitType *string `json:"tpmLimitType,omitempty" tf:"tpm_limit_type,omitempty"`
}

type TeamParameters struct {

	// List of pass-through routes this team is allowed to call.
	// +kubebuilder:validation:Optional
	AllowedPassthroughRoutes []*string `json:"allowedPassthroughRoutes,omitempty" tf:"allowed_passthrough_routes,omitempty"`

	// Whether the team is blocked from making requests. Default is false.
	// +kubebuilder:validation:Optional
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Duration for the budget cycle. Valid values are:
	// +kubebuilder:validation:Optional
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// List of guardrails applied to every request made by this team.
	// +kubebuilder:validation:Optional
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// Maximum budget allocated to the team.
	// +kubebuilder:validation:Optional
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// A map of string metadata key-value pairs associated with the team. tags and soft_budget_alerting_emails are stored by the proxy under metadata but are managed through their own attributes below, not this map.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Map of alias names to model names, letting the team call models under stable alias names.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelAliases map[string]*string `json:"modelAliases,omitempty" tf:"model_aliases,omitempty"`

	// Map of model name to requests per minute limit for that model.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Map of model name to tokens per minute limit for that model.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of model names that this team can access.
	// +kubebuilder:validation:Optional
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// The ID of the organization this team belongs to.
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// List of prompt IDs the team is allowed to use.
	// +kubebuilder:validation:Optional
	Prompts []*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// Team-wide requests per minute limit.
	// +kubebuilder:validation:Optional
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// How the RPM limit is enforced: guaranteed_throughput or best_effort_throughput. Changing this forces a new team to be created.
	// One of 'guaranteed_throughput' or 'best_effort_throughput'; only settable at creation
	// +kubebuilder:validation:Optional
	RpmLimitType *string `json:"rpmLimitType,omitempty" tf:"rpm_limit_type,omitempty"`

	// Spend threshold at which the proxy sends a soft budget alert without blocking requests.
	// Spend threshold that triggers a soft budget alert without blocking requests
	// +kubebuilder:validation:Optional
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// List of email addresses notified when the team's spend crosses soft_budget.
	// Email addresses alerted when the team crosses soft_budget
	// +kubebuilder:validation:Optional
	SoftBudgetAlertingEmails []*string `json:"softBudgetAlertingEmails,omitempty" tf:"soft_budget_alerting_emails,omitempty"`

	// List of tags applied to the team, used for spend tracking and tag-based routing.
	// Tags for spend tracking and tag-based routing
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A human-readable identifier for the team.
	// +kubebuilder:validation:Optional
	TeamAlias *string `json:"teamAlias,omitempty" tf:"team_alias,omitempty"`

	// A stable, human-readable ID for the team (for example platform-team). If omitted, the provider generates a random UUID. Changing this forces a new team to be created.
	// Unique ID for the team. Generated by the provider if not provided
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Budget (in USD) applied to each individual team member.
	// Budget applied to every team member
	// +kubebuilder:validation:Optional
	TeamMemberBudget *float64 `json:"teamMemberBudget,omitempty" tf:"team_member_budget,omitempty"`

	// Reset cycle for the per-member budget (e.g. 30d, 1mo).
	// +kubebuilder:validation:Optional
	TeamMemberBudgetDuration *string `json:"teamMemberBudgetDuration,omitempty" tf:"team_member_budget_duration,omitempty"`

	// Lifetime for keys created by team members (e.g. 1d, 1w).
	// +kubebuilder:validation:Optional
	TeamMemberKeyDuration *string `json:"teamMemberKeyDuration,omitempty" tf:"team_member_key_duration,omitempty"`

	// List of permissions granted to team members. This controls what actions team members can perform within the team context.
	// List of permissions granted to team members
	// +kubebuilder:validation:Optional
	TeamMemberPermissions []*string `json:"teamMemberPermissions,omitempty" tf:"team_member_permissions,omitempty"`

	// Requests per minute limit applied to each individual team member.
	// +kubebuilder:validation:Optional
	TeamMemberRpmLimit *float64 `json:"teamMemberRpmLimit,omitempty" tf:"team_member_rpm_limit,omitempty"`

	// Tokens per minute limit applied to each individual team member.
	// +kubebuilder:validation:Optional
	TeamMemberTpmLimit *float64 `json:"teamMemberTpmLimit,omitempty" tf:"team_member_tpm_limit,omitempty"`

	// Team-wide tokens per minute limit.
	// +kubebuilder:validation:Optional
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// How the TPM limit is enforced: guaranteed_throughput or best_effort_throughput. Changing this forces a new team to be created.
	// One of 'guaranteed_throughput' or 'best_effort_throughput'; only settable at creation
	// +kubebuilder:validation:Optional
	TpmLimitType *string `json:"tpmLimitType,omitempty" tf:"tpm_limit_type,omitempty"`
}

// TeamSpec defines the desired state of Team
type TeamSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamInitParameters `json:"initProvider,omitempty"`
}

// TeamStatus defines the observed state of Team.
type TeamStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Team is the Schema for the Teams API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Team struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.teamAlias) || (has(self.initProvider) && has(self.initProvider.teamAlias))",message="spec.forProvider.teamAlias is a required parameter"
	Spec   TeamSpec   `json:"spec"`
	Status TeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamList contains a list of Teams
type TeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Team `json:"items"`
}

// Repository type metadata.
var (
	Team_Kind             = "Team"
	Team_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Team_Kind}.String()
	Team_KindAPIVersion   = Team_Kind + "." + CRDGroupVersion.String()
	Team_GroupVersionKind = CRDGroupVersion.WithKind(Team_Kind)
)

func init() {
	SchemeBuilder.Register(&Team{}, &TeamList{})
}
