/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MemberAddInitParameters struct {

	// The maximum budget allocated for the team members.
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// One or more member blocks defining team members. Each block supports:
	Member []MemberAddMemberInitParameters `json:"member,omitempty" tf:"member,omitempty"`

	// The ID of the team to add members to.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`
}

type MemberAddMemberInitParameters struct {

	// The role of the user in the team. Must be one of: "admin" or "user".
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The email of the user to add to the team.
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// The ID of the user to add to the team.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type MemberAddMemberObservation struct {

	// The role of the user in the team. Must be one of: "admin" or "user".
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The email of the user to add to the team.
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// The ID of the user to add to the team.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type MemberAddMemberParameters struct {

	// The role of the user in the team. Must be one of: "admin" or "user".
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`

	// The email of the user to add to the team.
	// +kubebuilder:validation:Optional
	UserEmail *string `json:"userEmail,omitempty" tf:"user_email,omitempty"`

	// The ID of the user to add to the team.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type MemberAddObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The maximum budget allocated for the team members.
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// One or more member blocks defining team members. Each block supports:
	Member []MemberAddMemberObservation `json:"member,omitempty" tf:"member,omitempty"`

	// The ID of the team to add members to.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`
}

type MemberAddParameters struct {

	// The maximum budget allocated for the team members.
	// +kubebuilder:validation:Optional
	MaxBudgetInTeam *float64 `json:"maxBudgetInTeam,omitempty" tf:"max_budget_in_team,omitempty"`

	// One or more member blocks defining team members. Each block supports:
	// +kubebuilder:validation:Optional
	Member []MemberAddMemberParameters `json:"member,omitempty" tf:"member,omitempty"`

	// The ID of the team to add members to.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`
}

// MemberAddSpec defines the desired state of MemberAdd
type MemberAddSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MemberAddParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MemberAddInitParameters `json:"initProvider,omitempty"`
}

// MemberAddStatus defines the observed state of MemberAdd.
type MemberAddStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MemberAddObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MemberAdd is the Schema for the MemberAdds API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type MemberAdd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.teamId) || (has(self.initProvider) && has(self.initProvider.teamId))",message="spec.forProvider.teamId is a required parameter"
	Spec   MemberAddSpec   `json:"spec"`
	Status MemberAddStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MemberAddList contains a list of MemberAdds
type MemberAddList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MemberAdd `json:"items"`
}

// Repository type metadata.
var (
	MemberAdd_Kind             = "MemberAdd"
	MemberAdd_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MemberAdd_Kind}.String()
	MemberAdd_KindAPIVersion   = MemberAdd_Kind + "." + CRDGroupVersion.String()
	MemberAdd_GroupVersionKind = CRDGroupVersion.WithKind(MemberAdd_Kind)
)

func init() {
	SchemeBuilder.Register(&MemberAdd{}, &MemberAddList{})
}
