//go:build !ignore_autogenerated

/*
Copyright 2024 Corewire.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Store) DeepCopyInto(out *Store) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Store.
func (in *Store) DeepCopy() *Store {
	if in == nil {
		return nil
	}
	out := new(Store)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Store) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreInitParameters) DeepCopyInto(out *StoreInitParameters) {
	*out = *in
	if in.CustomLlmProvider != nil {
		in, out := &in.CustomLlmProvider, &out.CustomLlmProvider
		*out = new(string)
		**out = **in
	}
	if in.LitellmCredentialName != nil {
		in, out := &in.LitellmCredentialName, &out.LitellmCredentialName
		*out = new(string)
		**out = **in
	}
	if in.LitellmParams != nil {
		in, out := &in.LitellmParams, &out.LitellmParams
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VectorStoreDescription != nil {
		in, out := &in.VectorStoreDescription, &out.VectorStoreDescription
		*out = new(string)
		**out = **in
	}
	if in.VectorStoreMetadata != nil {
		in, out := &in.VectorStoreMetadata, &out.VectorStoreMetadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VectorStoreName != nil {
		in, out := &in.VectorStoreName, &out.VectorStoreName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreInitParameters.
func (in *StoreInitParameters) DeepCopy() *StoreInitParameters {
	if in == nil {
		return nil
	}
	out := new(StoreInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreList) DeepCopyInto(out *StoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Store, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreList.
func (in *StoreList) DeepCopy() *StoreList {
	if in == nil {
		return nil
	}
	out := new(StoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreObservation) DeepCopyInto(out *StoreObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.CustomLlmProvider != nil {
		in, out := &in.CustomLlmProvider, &out.CustomLlmProvider
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LitellmCredentialName != nil {
		in, out := &in.LitellmCredentialName, &out.LitellmCredentialName
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
	if in.VectorStoreDescription != nil {
		in, out := &in.VectorStoreDescription, &out.VectorStoreDescription
		*out = new(string)
		**out = **in
	}
	if in.VectorStoreID != nil {
		in, out := &in.VectorStoreID, &out.VectorStoreID
		*out = new(string)
		**out = **in
	}
	if in.VectorStoreMetadata != nil {
		in, out := &in.VectorStoreMetadata, &out.VectorStoreMetadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VectorStoreName != nil {
		in, out := &in.VectorStoreName, &out.VectorStoreName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreObservation.
func (in *StoreObservation) DeepCopy() *StoreObservation {
	if in == nil {
		return nil
	}
	out := new(StoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreParameters) DeepCopyInto(out *StoreParameters) {
	*out = *in
	if in.CustomLlmProvider != nil {
		in, out := &in.CustomLlmProvider, &out.CustomLlmProvider
		*out = new(string)
		**out = **in
	}
	if in.LitellmCredentialName != nil {
		in, out := &in.LitellmCredentialName, &out.LitellmCredentialName
		*out = new(string)
		**out = **in
	}
	if in.LitellmParamsSecretRef != nil {
		in, out := &in.LitellmParamsSecretRef, &out.LitellmParamsSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.VectorStoreDescription != nil {
		in, out := &in.VectorStoreDescription, &out.VectorStoreDescription
		*out = new(string)
		**out = **in
	}
	if in.VectorStoreMetadata != nil {
		in, out := &in.VectorStoreMetadata, &out.VectorStoreMetadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VectorStoreName != nil {
		in, out := &in.VectorStoreName, &out.VectorStoreName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreParameters.
func (in *StoreParameters) DeepCopy() *StoreParameters {
	if in == nil {
		return nil
	}
	out := new(StoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSpec) DeepCopyInto(out *StoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSpec.
func (in *StoreSpec) DeepCopy() *StoreSpec {
	if in == nil {
		return nil
	}
	out := new(StoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreStatus) DeepCopyInto(out *StoreStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreStatus.
func (in *StoreStatus) DeepCopy() *StoreStatus {
	if in == nil {
		return nil
	}
	out := new(StoreStatus)
	in.DeepCopyInto(out)
	return out
}
