/*
Copyright 2024 Corewire.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type StoreInitParameters struct {

	// The vector store provider. Supported values: "bedrock", "openai", "azure", "vertex_ai", "pgvector".
	// Custom LLM provider for the vector store
	CustomLlmProvider *string `json:"customLlmProvider,omitempty" tf:"custom_llm_provider,omitempty"`

	// Name of the LiteLLM credential to use for authentication.
	// Name of the LiteLLM credential to use
	LitellmCredentialName *string `json:"litellmCredentialName,omitempty" tf:"litellm_credential_name,omitempty"`

	LitellmParams map[string]*string `json:"litellmParamsSecretRef,omitempty" tf:"-"`

	// Description of the vector store.
	// Description of the vector store
	VectorStoreDescription *string `json:"vectorStoreDescription,omitempty" tf:"vector_store_description,omitempty"`

	// Map of metadata associated with the vector store.
	// Metadata associated with the vector store
	// +mapType=granular
	VectorStoreMetadata map[string]*string `json:"vectorStoreMetadata,omitempty" tf:"vector_store_metadata,omitempty"`

	// Name of the vector store.
	// Name of the vector store
	VectorStoreName *string `json:"vectorStoreName,omitempty" tf:"vector_store_name,omitempty"`
}

type StoreObservation struct {

	// Timestamp when the vector store was created.
	// Timestamp when the vector store was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The vector store provider. Supported values: "bedrock", "openai", "azure", "vertex_ai", "pgvector".
	// Custom LLM provider for the vector store
	CustomLlmProvider *string `json:"customLlmProvider,omitempty" tf:"custom_llm_provider,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the LiteLLM credential to use for authentication.
	// Name of the LiteLLM credential to use
	LitellmCredentialName *string `json:"litellmCredentialName,omitempty" tf:"litellm_credential_name,omitempty"`

	// Timestamp when the vector store was last updated.
	// Timestamp when the vector store was last updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Description of the vector store.
	// Description of the vector store
	VectorStoreDescription *string `json:"vectorStoreDescription,omitempty" tf:"vector_store_description,omitempty"`

	// The unique identifier of the vector store.
	// Unique identifier for the vector store
	VectorStoreID *string `json:"vectorStoreId,omitempty" tf:"vector_store_id,omitempty"`

	// Map of metadata associated with the vector store.
	// Metadata associated with the vector store
	// +mapType=granular
	VectorStoreMetadata map[string]*string `json:"vectorStoreMetadata,omitempty" tf:"vector_store_metadata,omitempty"`

	// Name of the vector store.
	// Name of the vector store
	VectorStoreName *string `json:"vectorStoreName,omitempty" tf:"vector_store_name,omitempty"`
}

type StoreParameters struct {

	// The vector store provider. Supported values: "bedrock", "openai", "azure", "vertex_ai", "pgvector".
	// Custom LLM provider for the vector store
	// +kubebuilder:validation:Optional
	CustomLlmProvider *string `json:"customLlmProvider,omitempty" tf:"custom_llm_provider,omitempty"`

	// Name of the LiteLLM credential to use for authentication.
	// Name of the LiteLLM credential to use
	// +kubebuilder:validation:Optional
	LitellmCredentialName *string `json:"litellmCredentialName,omitempty" tf:"litellm_credential_name,omitempty"`

	// Map of additional parameters specific to the vector store provider. Do not put API keys or other secrets here; this map is stored unencrypted in state. Store secrets in a litellm_credential and reference it via litellm_credential_name.
	// Additional LiteLLM parameters
	// +kubebuilder:validation:Optional
	LitellmParamsSecretRef *v1.SecretReference `json:"litellmParamsSecretRef,omitempty" tf:"-"`

	// Description of the vector store.
	// Description of the vector store
	// +kubebuilder:validation:Optional
	VectorStoreDescription *string `json:"vectorStoreDescription,omitempty" tf:"vector_store_description,omitempty"`

	// Map of metadata associated with the vector store.
	// Metadata associated with the vector store
	// +kubebuilder:validation:Optional
	// +mapType=granular
	VectorStoreMetadata map[string]*string `json:"vectorStoreMetadata,omitempty" tf:"vector_store_metadata,omitempty"`

	// Name of the vector store.
	// Name of the vector store
	// +kubebuilder:validation:Optional
	VectorStoreName *string `json:"vectorStoreName,omitempty" tf:"vector_store_name,omitempty"`
}

// StoreSpec defines the desired state of Store
type StoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StoreInitParameters `json:"initProvider,omitempty"`
}

// StoreStatus defines the observed state of Store.
type StoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Store is the Schema for the Stores API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Store struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.customLlmProvider) || (has(self.initProvider) && has(self.initProvider.customLlmProvider))",message="spec.forProvider.customLlmProvider is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vectorStoreName) || (has(self.initProvider) && has(self.initProvider.vectorStoreName))",message="spec.forProvider.vectorStoreName is a required parameter"
	Spec   StoreSpec   `json:"spec"`
	Status StoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StoreList contains a list of Stores
type StoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Store `json:"items"`
}

// Repository type metadata.
var (
	Store_Kind             = "Store"
	Store_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Store_Kind}.String()
	Store_KindAPIVersion   = Store_Kind + "." + CRDGroupVersion.String()
	Store_GroupVersionKind = CRDGroupVersion.WithKind(Store_Kind)
)

func init() {
	SchemeBuilder.Register(&Store{}, &StoreList{})
}
