apiVersion: litellm.litellm.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: litellm/v1alpha1/key
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    keyAlias: prod-key-1
    models:
    - gpt-4-proxy
    maxBudget: 100
    budgetDuration: monthly
    duration: 30d
    rpmLimit: 60
    tpmLimit: 1000
  providerConfigRef:
    name: default
