apiVersion: litellm.crossplane.io/v1alpha1
kind: Organization
metadata:
  name: e2e-organization
spec:
  forProvider:
    organizationAlias: e2e-org
    maxBudget: 2000
    models:
    - gpt-4
  providerConfigRef:
    name: default
