apiVersion: litellm.litellm.crossplane.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: litellm/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: openai_cred
  name: openai-cred
spec:
  forProvider:
    credentialInfo:
      provider: openai
      purpose: chat-completions
      region: us-east-1
    credentialName: openai-api-key
    credentialValuesSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    modelId: gpt-4
